### ISSUE TITLE
Need to customize headers

### ISSUE THREAD

**Issue by samwarfield** [IBM-Swift/Kitura-OpenAPI#24] opened 2019-04-22 14:31 UTC
I need to add some custom headers with a JWT token and basic username/password.

**Comment by ianpartridge** [comment] 2019-07-08 14:44
Sorry for the delay, could you explain a bit more about what you mean?

**Comment by samwarfield** [comment] 2019-07-08 14:47
No worries. I need to be able to set header fields from the Swagger UI...

I was able to figure out how to add query params...

**Comment by samwarfield** [comment] 2019-07-08 14:52
Maybe I need a way to override the generated swagger and edit it.

I sometimes have an endpoint where I need to add a custom header field.

**Comment by ianpartridge** [comment] 2019-07-08 14:53
Thanks. Unfortunately this isn't supported at the moment. We'd need a way to teach the Swagger generator about header parameters and it doesn't know about that :( Kitura's codable routing feature doesn't allow the user to specify header parameters either, so this is rather a large problem...

**Comment by samwarfield** [comment] 2019-07-08 14:55
Is it possilbe to setup a way to edit the generated swagger to work around this?

**Comment by ianpartridge** [comment] 2019-07-08 15:03
You can access the generated Swagger through `router.swaggerJSON`, so perhaps you could do something with that?  I can't think how you could get SwaggerUI to pick up your edited Swagger though..

**Comment by ianpartridge** [comment] 2019-07-16 15:41
I'm going to close this for the moment as the issue is fundamentally in Kitura's codable routing itself and the Swagger generator, not this package.

**Closed by ianpartridge** 2019-07-16 15:41 UTC
